builders:
  addon_builder:
    import: "package:arceus_addon_dependencies/builder.dart"
    builder_factories: ["AddonBuilder"]
    builders: { r"$lib$": ["*.evc"] }
    build_to: cache
    auto_apply: dependents
