builders:
  addon_builder:
    import: "package:arceus_addon_dependencies/builder.dart"
    builder_factories: ["getAddonBuilder"]
    build_to: source
    build_extensions: { ".placeholder": ["build/output.evc"] }
    auto_apply: dependents
