name: arceus_addon_dependencies
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0-180.3.beta

dependencies:
  dart_eval: any
  glob: ^2.1.2
  source_gen: ^1.5.0
  yaml: any

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  build_runner: any
